### ISSUE TITLE
input-validate lambda trying to parse invalid JSON

### ISSUE THREAD

**Issue by jaredjj3** [aws-solutions/video-on-demand-on-aws#134]
**Describe the bug**
The input-validate is trying to parse `'Yes' | 'No'` parameters as JSON.

- [Environment specification in cloudformation template](https://github.com/awslabs/video-on-demand-on-aws/blob/master/deployment/video-on-demand-on-aws.yaml#L727)
- [input-validate function](https://github.com/awslabs/video-on-demand-on-aws/blob/master/source/input-validate/index.js#L36)
- Affected environment variables: `FrameCapture`, `EnableMediaPackage`, `EnableSns`, `EnableSqs`

**To Reproduce**
1. Deploy stack from commit `4b42a547c9acbdf959e3495d3389b610c5d8acd7`
1. Upload a file into the video source bucket
1. Assert that the lambda input-validate function fails

**Expected behavior**
The lambda input-validate function handles `'Yes' | 'No'` correctly OR the environment variables are set to be JSON-parseable.

**Please complete the following information about the solution:**
- Version: 5.2.0
- Region: us-east-1
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [X] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [X] Were there any errors in the CloudWatch Logs?

**Screenshots**
![image](https://user-images.githubusercontent.com/19232300/127780967-676596f1-81eb-47d5-84de-d0187ef6f21c.png)

**Additional context**
Exception:

```
Error

SyntaxError
Cause

{
  "errorType": "SyntaxError",
  "errorMessage": "Unexpected token N in JSON at position 0",
  "trace": [
    "SyntaxError: Unexpected token N in JSON at position 0",
    "    at JSON.parse (<anonymous>)",
    "    at Runtime.exports.handler (/var/task/index.js:36:32)",
    "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
  ]
}
```

To fix this, I forked from this repo added conditions to the template, then transformed the boolean parameters to strings that are JSON-parseable for the input-validate environment:

```yaml
      Environment:
        Variables:
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
          ErrorHandler: !GetAtt ErrorHandler.Arn
          WorkflowName: !Ref AWS::StackName
          Source: !Ref Source
          Destination: !Ref Destination
          FrameCapture: !If
            - IsFrameCaptureEnabled
            - 'true'
            - 'false'
          ArchiveSource: !Ref Glacier
          MediaConvert_Template_2160p: !If
            - IsMediaPackageEnabled
            - !Sub '${AWS::StackName}_Ott_2160p_Avc_Aac_16x9_mvod_no_preset'
            - !Sub '${AWS::StackName}_Ott_2160p_Avc_Aac_16x9_qvbr_no_preset'
          MediaConvert_Template_1080p: !If
            - IsMediaPackageEnabled
            - !Sub '${AWS::StackName}_Ott_1080p_Avc_Aac_16x9_mvod_no_preset'
            - !Sub '${AWS::StackName}_Ott_1080p_Avc_Aac_16x9_qvbr_no_preset'
          MediaConvert_Template_720p: !If
            - IsMediaPackageEnabled
            - !Sub '${AWS::StackName}_Ott_720p_Avc_Aac_16x9_mvod_no_preset'
            - !Sub '${AWS::StackName}_Ott_720p_Avc_Aac_16x9_qvbr_no_preset'
          CloudFront: !GetAtt CloudFront.DomainName
          EnableMediaPackage: !If
            - IsMediaPackageEnabled
            - 'true'
            - 'false'
          InputRotate: DEGREE_0
          EnableSns: !If
            - IsSnsEnabled
            - 'true'
            - 'false'
          EnableSqs: !If
            - IsSqsEnabled
            - 'true'
            - 'false'
          AcceleratedTranscoding: !Ref AcceleratedTranscoding
```
